export const countryName = 'Australia'
export const editAccountUserNameTxt = 'S'
export const searchValue = 'pay'
export const rating = 'Rating'
export const price = 'Price'
export const itemName = 'Name'
